### PR TITLE
Init: load gresourced styles if present

### LINKED ISSUE #643: Adw apps don't automatically load styles with Granite.init ()
### What Happened?

Adwaita has a feature that will automatically load stylesheet gresources named `style.css` or `style-dark.css`, but this is disabled when Granite is initialized, meaning apps like font-viewer lose their custom CSS that the app expects.

https://gitlab.gnome.org/GNOME/libadwaita/-/commit/d671a1f4ef76968a5b62b20557ea28628905a58b

### Steps to Reproduce

Build a LibAdwaita app using Granite.init such as https://github.com/elementary/font-viewer/pull/6

See that the app's custom styles are missing

### Expected Behavior

We should probably just provide this same feature 

### OS Version

7.x (Horus)

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #643

Try to find a `style.css` file and if it exists, add it as an `APPLICATION` priority

### CODE REVIEW

**Comment by Marukesu** [comment]
I believe this would make epiphany load they `style.css`, maybe `style-elementary.css` like epiphany does, or the `Application.css` that's already used by elementary apps should be a better name.

**Comment by Exalm** [comment]
It would, yeah. Not nice that there is a style clash, but not a lot we can do here. :(

Any reason not to have a dark variant as well? libadwaita does have that too

**Comment by danirabbit** [comment]
@Marukesu @Exalm Yeah maybe we can check for `Application.css` or `style-elementary.css` first and then try `style.css` if it isn't available? The problem is that for apps like font viewer, we need the padding etc that they provide in their `style.css`

@Exalm I just wanted to get the minimum in here first and then come back in a separate branch for dark style loading since it introduces quite a bit more complexity

**Comment by Marukesu** [comment]
In the font viewer case, could we patch the gresource file to alias the `style.css` to the expected name by granite?

**Comment by danirabbit** [comment]
Ah yeah that's true. In that case, I'll change this to look for `Application.css` which is the convention we've been using so far in our apps

**Review by Marukesu — APPROVED** [review]
LGTM.

**Pull request merged**
