### PR TITLE
Demo disable options 

### PR DESCRIPTION
**Pull request by paledega**
We can disable demo subdir building.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
Hey, first of all thanks for your contribution! Is there a specific need or a problem that you are trying to solve by disabling the demo? It's not like it takes multiple minutes to compile the demo app, so I'm curious as to why this extra option is needed

**Comment by paledega** [comment]
demo cannot compile with non english locale 
https://github.com/elementary/granite/issues/424
we have 2 way to fix this

1. change LANG variable 

2. disable demo

also developers may not need demo part

**Comment by paledega** [comment]
```shell
[74/75] Generating Granite-1.0.typelib with a custom command lib/Granite-1.0.

Just/in/g-ir-compiler .-shared-library 1ib granite.so.5.5.0 --output lib/Granite-1.0.typelib /home/efel.cache/yay/granite-git/ ** (g-ir-compiler: 98480): ERROR *: 16:23:00.443: Invalid typelib for module "Granite': In directory (Context: Serviceslogleve [75/75] Linking target demo/granite-demo

d/lib/Granite-1.0.gir /home/efe/.cache/yay/granite-git/src/build/lib/Granite-1.0.gir:1895:1: warning: element field from state 7 is unknown, ignoring

value contains invalid characters: ınfo'

ninja: build stopped subcommand failed. HATA: build() içinde bir hata oluştu.

Çıkılıyor..: error making: X!s(func) string=0x55de058aeedo)


```

**Comment by danrabbit** [comment]
This was fixed upstream in Vala: https://gitlab.gnome.org/GNOME/vala/-/issues/1067

Closing as "Out of scope"

**Pull request closed without merging**
