### PR TITLE
Demo: Replace Granite.Avatar with Gtk.Spinner

### PR DESCRIPTION
**Pull request by danrabbit**
Get rid of deprecated Granite.Avatar but without adding a Hdy dep to the demo

### CODE REVIEW

**Comment by hanaral** [comment]
You better round those corners while ur at it then

**Comment by cassidyjames** [comment]
@hanaral 

>**without** adding a Hdy dep

**Comment by cassidyjames** [comment]
Derp wrong button

**Comment by hanaral** [comment]
> @hanaral 
> 
> 
> 
> >**without** adding a Hdy dep

It is too late for me to be on gh rn 😑

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
