### PR TITLE
Increased required vala compiler version

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #492

### CODE REVIEW

**Review by jeremypw — APPROVED** [review]
Did it fix your problem building on Hera? 

Anyway it needs to be done.

**Comment by peteruithoven** [comment]
As far as I know I can't easily install a newer version of the Vala compiler, but now at least it gives a clear warning:
```
meson.build:9:4: ERROR:  Problem encountered: vala compiler version 0.48.0 or newer is required.
```

**Comment by jeremypw** [comment]
You have to install a ppa to get the later versions (at least, that is what I did). See https://launchpad.net/~vala-team/+archive/ubuntu/next

**Comment by peteruithoven** [comment]
Ah good point! (I've been mostly doing web front-end development, so I'm a bit rusty)

I'm not able to install the latest version of the vala compiler from that ppa, but github isn't a good place for such questions so I opened another stack exchange question: 
https://elementaryos.stackexchange.com/questions/27859/how-to-install-newer-vala-compiler

**Pull request merged**
