### PR TITLE
Make Toast Wrap

### PR DESCRIPTION
**Pull request by ZenitsuDev**
When the 'Grantie.Toast' title gets too long, for example when used to toast long filenames, the 'Granite.Toast' continues to expand horizontally regardless of the parent window. This aims to fix it.

**Before** 
Screenshot from 2022-05-26 08 28 44

**After**
Screenshot from 2022-05-26 08 42 24

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
This causes a problem when the toast is not a simple label
Screenshot from 2022-06-08 18 14 34
In master, the demo toast does not wrap.

**Comment by jeremypw** [comment]
The solution seems to be to add `natural_wrap_mode = Gtk.NaturalWrapMode.NONE` to the properties of the `notification_label`.

**Comment by ZenitsuDev** [comment]
@jeremypw would it be bad to add something like:
`if (parent is Gtk.Overlay) {
    ((Gtk.Overlay) parent).set_measure_overlay (this, true);
}`

**Comment by jeremypw** [comment]
@ZenitsuDev I have tried it both ways with the `main` branch of the `io.elementary.music` which is the only elementary project currently using a Toast and Granite-7.   If you do not `set_measure_overlay` then the toast extends outside the left-hand pane (the queue) but otherwise nothing bad happens.  On balance, I think it better to leave each toast user to decide whether or not `set_measure_overlay` is needed in their particular case rather than try to be too clever about it.

**Comment by ZenitsuDev** [comment]
It seems fixed to me now. Thank you @jeremypw . Is it for you too?

**Review by jeremypw — APPROVED** [review]
Looks good now - thanks!

**Pull request merged**
