### PR TITLE
HeaderLabel: set accessible description

### PR DESCRIPTION
**Pull request by danirabbit**
Properly set secondary text as a description

### CODE REVIEW

**Review by zeebok — APPROVED** [review]
This works as advertised though I wonder if it is better for the secondary text to become the description of the primary label, so it would be Name: Username and Description: Must be at least 8 characters long. Not sure how it all appears for the end user.

**Comment by danirabbit** [comment]
@zeebok the labels themselves aren't actually available to the screen reader. So what happens is you have to set a mnemonic widget and then when that widget gets focus it reads out the accessible name, the type of widget, then the accessible description. So for example if the mnemonic widget was a text entry it would say:

"Username Text. Must be at least 8 characters long"

**Comment by zeebok** [comment]
Gotcha. Looking via the Inspector it has the secondary text as a different label that is a sibling of the primary and so each one has its own name in the accessibility data tab, so I wasn't sure if that is how it will appear with the screen reader

**Comment by danirabbit** [comment]
Oh hm yeah I'm not sure how the whole a11y tree stuff works, but I'll take a look at it!

**Comment by danirabbit** [comment]
I'm gonna go ahead and merge this for now since after double checking with Florian it seems the label order is correct here

**Pull request merged**
