### PR TITLE
Expose tab label tooltip

### PR DESCRIPTION
**Pull request by jeremypw**
Allow apps to set a tooltip with additional information rather than just repeating information that is already visible in the tab label (although the label could be ellipsized)

### CODE REVIEW

**Comment by danrabbit** [comment]
Seems reasonable :) Can we add this to the demo?

**Comment by jeremypw** [comment]
Sure, I'll do that.

**Review by danrabbit — APPROVED** [review]
Looks good :+1:

**Review by danrabbit — CHANGES_REQUESTED** [review]
Oh I almost forgot. It needs a comment for generating docs :)

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
