### PR TITLE
implement filled tab-bar

### PR DESCRIPTION
**Pull request by andreasfelix**
Fixes: #239
Also fixes: #17, #220, #221

Removes the functionality to create a new tab (restore the last closed tab) when double-clicking (middle/three-finger clicking) on an empty part of tab-bar.

Files
Code
Terminal

Suggestions welcome!

**Open Design Decisions:**
- [ ] Should hovering over the `add_button` resize tabs?
- [ ] Should a single tab be resized instantly (while still hovering over tab-bar)?
- [ ] Should the `close_tab_button` be visible for a single tab (without hovering)?
- [ ] Should there be a resize animation?

**Implementation:**
- closing a tab with a `close_button` or `middle_click` freezes the current
  tab width and sets the `need_to_expand` flag
- leaving the tab-bar will expand the tabs again, if the `need_to_expand` flag is set
- the current `PageTabContainer`, the `DynamicNotebook` and the `add_tab_button` are used to signal the `leave_tab_bar_event`
- this can be done as:
        *tab_bar_area* **=** *dynamic_notbook_area* **-** *current_page_tab_container_area* **-** *add_tab_button_area*
- so leaving the `DynamicNotebook`, entering the current `TabPageContainer` or entering the `add_tab_button`  will cause a check if the tabs have to be expanded again (equivalent to leave_tab_bar_event)

### CODE REVIEW

**Comment by andreasfelix** [comment]
last two commits also fix #82

The problem of #82 was that the middle-click `button_press_event` was not consumed by the tab and the event was propagated to notebook. 

Even though the middle/click on tab can't conflict with middle-click on notebook for the filled tab bar, I added a line to explicitly consume this event.

**Comment by andreasfelix** [comment]
I played around with the style in the inpsector, so that a single filled tab has no border. What do you think?

changes style
change_style code

**CSS:**
```css
notebook tab:nth-child(2):nth-last-child(2) {
    border: none;
    border-width: none;
    background: none;
    box-shadow: none;
}
```

**Comment by donadigo** [comment]
I personally don't like this change. It seems way harder to scan what tabs you have currently open because they are much wider and have the same styling. I believe that we're aiming for having tabs behave as closely as possible to how Chrome does it.

I think there's two changes from this PR that would be definitely accepted:
* increased default maximum width for tabs
* do not resize tabs when closing them on hover

**Comment by andreasfelix** [comment]
@donadigo A counterargument would be, that you only  have to really scan the tab-bar if more than 3 tabs are open. And in this case the tabs are not much wider anyway.

The main argument for the filled tabs is, that it would allow display longer labels. This would be especially helpful for code/files, in the case you two files with the same name. (see below for gala example)

**Currently**
code small

**Filled tabs** (optional folder name has to be implemented)
filled

Another possibility would be to make the tab width depend on the current label. (look at vscode)

A fourth option would be a combination be a filled tab bar, where tabs which need more space would be wider than others.

**Comment by glimpster** [comment]
Great stuff Felix!

**Comment by andreasfelix** [comment]
As I see it, there are 4 different options, which would solve the problem of the non-readable tabs:

1. non-filled equal-spaced tabs with larger minimum width
2. non-filled variable-spaced tabs (similar to vscode, where tabs can have different width)
3. filled equal-spaced tabs (this PR)
4. filled variable-spaced tabs

I would be ok to change this PR to any of them, but I personally prefer 3 or 4.

Another question is if the tab size should depend on the window width. Currently the tab-width gets updated whenever the window size changes:

https://github.com/elementary/granite/blob/f5590325f92430d8b8c88d175a99119306c76bc3/lib/Widgets/DynamicNotebook.vala#L841-L843

What is the point of seeing all tabs at once when you can't read the label? I would rather click the arrow-button then having tab labels with "Do...ds" and "Do..nts". At least, I think there should be a minimum width so that normal length labels don't get truncated.

---

How 4. would look like:

filled_with_variable_width

**Comment by jlnr** [comment]
I like the GIF variable-spaced tabs in Code (approach 2), but I think it would be distracting in Epiphany, Terminal, and Files, where tabs change their titles while navigating around.

Since Code already uses a different tab style, I wouldn't mind if it adopted variable-spaced tabs (probably implemented as an option here in Granite), but I'm not sure if it should be the default.

**Comment by andreasfelix** [comment]
Good point, I didn't thought about this! So variable-spaced tabs only make sense for static labels and changing labels should always be same width.

I could implement an option, so that the different applications could chose between the 4 different tab-styles. This could be simple done with two bools `filled_tab_bar` and `equal_spaced_tabs`.

**Comment by jlnr** [comment]
Hey @andreasfelix, I've just closed #239. It was good to have an implementation of filled tabs to play around with, but the UX team consensus was that filling the whole tab bar is too much.

I would still love to see #17 and the other issues fixed, and maybe you can also re-target this PR to increase the initial tab width? The current default size can definitely feel cramped, especially with "Larger" fonts. (Could the font size maybe be taken into account for the initial tab width?)

Variable tab width seems like a separate feature request that would also need consideration from the UX team. Before this PR gets too messy, I would suggest opening a new issue for that in granite, even if it mostly applies to Code for now.

**Comment by andreasfelix** [comment]
Should this initial tab width depend on the the current window width? If not there would be one static tab width, which would automatically solve #17. 

Also #221 was only solved as a side effect when removing the functionality to create a new tab (restore the last closed tab) when double-clicking (middle/three-finger clicking) on an empty part of tab-bar. So it will remain for the non-filled tab bar.

**Comment by jlnr** [comment]
@andreasfelix I don't think the initial tab width should depend on the window width (unless the window is like 50px wide). #17 is still relevant because, even though tabs can't _grow_ indefinitely, they do still _shrink_, and that's when the same-width magic can kick in.

So basically, tab widths should be dynamic, but with an upper limit that is somewhere above the current default size (not sure what feels reasonable, maybe 150% of what it is now?).

**Comment by andreasfelix** [comment]
@jlnr I did moved the delay and the larger min/max tab width to a new PR (#311).

**Pull request closed without merging**
